server.port=8081
# Configuración del servidor

# Configuración de MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=vehiclesdb

# Opcional: Si tu MongoDB requiere autenticación
# spring.data.mongodb.username=usuario
# spring.data.mongodb.password=contraseña
# spring.data.mongodb.authentication-database=admin

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.example.vehicleapi=DEBUG

# Configuración de la aplicación
spring.application.name=Vehicle API
